server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: msvc-course
  datasource:
    url: jdbc:postgresql://localhost:5432/msvc_course
    username: afrivera
    password: afrivera
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: postgresql

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
