server:
  port: 8080

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: students
          uri: http://localhost:8581/
          predicates:
            - Path=/Student/v1/**
        - id: courses
          uri: http://localhost:8580/
          predicates:
            - Path=/Course/v1/**