server:
  port: 8080

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: students
          uri: lb://msvc-student
          predicates:
            - Path=/Student/v1/**
        - id: courses
          uri: lb://msvc-course
          predicates:
            - Path=/Course/v1/**