server:
  port: 8581

spring:
  application:
    name: msvc-student
  datasource:
    url: jdbc:mysql://localhost:3306/msvc_student
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: create

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka